### ISSUE TITLE
Bug: snapping to wrong location after changing direction

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Cheticamp/SnapToBlockDemo#1]
This occurs whether I do it by scrolling myself, or by using the toolbar buttons.
See attached video:
[device-2018-01-30-101402.zip](https://github.com/Cheticamp/SnapToBlockDemo/files/1676790/device-2018-01-30-101402.zip)

Tested on Pixel 2 with Android 8.1

**Comment by Cheticamp** [comment]
The fix to SnapToBlock has been applied and is in the repository.

**Comment by AndroidDeveloperLB** [comment]
Nice.
Can you please also check the instant-scroll functionality?
It had weird issues when I tried it using stable ids.

**Comment by Cheticamp** [comment]
Are you referring to the scroll with offset problem? If so, that is a problem because Android does not invoke the scroll listener after a scroll with offset. Since `SnapHelper` relies on the scroll listener, it can't snap without it. The fix, really a workaround, is to start the scroll with offset and set a global layout listener to do a "scroll to position" after the layout completes. "Scroll to position", does call the scroll listener, so all is well.

**Comment by AndroidDeveloperLB** [comment]
As I remember, there are 2 ways to do instant scrolls.
Anyway, why does it matter the part of the snapping?
Can't you temporary disable it when I request to scroll? 
Can you please put instant scroll solution into the sample?
